package com.mk.portal.framework.entity;
// Generated 10 Jul, 2015 4:31:26 PM by Hibernate Tools 3.2.2.GA



/**
 * CSSMappingEntity generated by hbm2java
 */
public class CSSMappingEntity  implements java.io.Serializable {


     private String id;
     private String siteId;
     private String pageId;
     private String cssPath;

    public CSSMappingEntity() {
    }

	
    public CSSMappingEntity(String id, String siteId, String cssPath) {
        this.id = id;
        this.siteId = siteId;
        this.cssPath = cssPath;
    }
    public CSSMappingEntity(String id, String siteId, String pageId, String cssPath) {
       this.id = id;
       this.siteId = siteId;
       this.pageId = pageId;
       this.cssPath = cssPath;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
    public String getPageId() {
        return this.pageId;
    }
    
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }
    public String getCssPath() {
        return this.cssPath;
    }
    
    public void setCssPath(String cssPath) {
        this.cssPath = cssPath;
    }




}


