package com.mk.portal.framework.entity;
// Generated 2 Aug, 2015 6:35:28 AM by Hibernate Tools 3.2.2.GA



/**
 * ExternalFilePathEntity generated by hbm2java
 */
public class ExternalFilePathEntity  implements java.io.Serializable {


     private String id;
     private String fileType;
     private String filePath;

    public ExternalFilePathEntity() {
    }

	
    public ExternalFilePathEntity(String id, String fileType) {
        this.id = id;
        this.fileType = fileType;
    }
    public ExternalFilePathEntity(String id, String fileType, String filePath) {
       this.id = id;
       this.fileType = fileType;
       this.filePath = filePath;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }




}


