package com.mk.portal.framework.entity;
// Generated 2 Aug, 2015 6:35:28 AM by Hibernate Tools 3.2.2.GA



/**
 * LinkEntity generated by hbm2java
 */
public class LinkEntity  implements java.io.Serializable {


     private String id;
     private String text;
     private String url;
     private String alt;
     private String siteId;
     private boolean isVisible;
     private String parentId;

    public LinkEntity() {
    }

	
    public LinkEntity(String id, String text, String alt, String siteId, boolean isVisible, String parentId) {
        this.id = id;
        this.text = text;
        this.alt = alt;
        this.siteId = siteId;
        this.isVisible = isVisible;
        this.parentId = parentId;
    }
    public LinkEntity(String id, String text, String url, String alt, String siteId, boolean isVisible, String parentId) {
       this.id = id;
       this.text = text;
       this.url = url;
       this.alt = alt;
       this.siteId = siteId;
       this.isVisible = isVisible;
       this.parentId = parentId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getAlt() {
        return this.alt;
    }
    
    public void setAlt(String alt) {
        this.alt = alt;
    }
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
    public boolean isIsVisible() {
        return this.isVisible;
    }
    
    public void setIsVisible(boolean isVisible) {
        this.isVisible = isVisible;
    }
    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }




}


