package com.mk.portal.framework.entity;
// Generated 24 Jul, 2015 2:29:11 PM by Hibernate Tools 3.2.2.GA



/**
 * PageEntity generated by hbm2java
 */
public class PageEntity  implements java.io.Serializable {


     private String pageId;
     private String siteId;
     private String pageTitle;
     private boolean enabled;
     private String pageUrl;
     private String pageLinkId;

    public PageEntity() {
    }

	
    public PageEntity(String pageId, String siteId, boolean enabled, String pageUrl, String pageLinkId) {
        this.pageId = pageId;
        this.siteId = siteId;
        this.enabled = enabled;
        this.pageUrl = pageUrl;
        this.pageLinkId = pageLinkId;
    }
    public PageEntity(String pageId, String siteId, String pageTitle, boolean enabled, String pageUrl, String pageLinkId) {
       this.pageId = pageId;
       this.siteId = siteId;
       this.pageTitle = pageTitle;
       this.enabled = enabled;
       this.pageUrl = pageUrl;
       this.pageLinkId = pageLinkId;
    }
   
    public String getPageId() {
        return this.pageId;
    }
    
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
    public String getPageTitle() {
        return this.pageTitle;
    }
    
    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public String getPageUrl() {
        return this.pageUrl;
    }
    
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }
    public String getPageLinkId() {
        return this.pageLinkId;
    }
    
    public void setPageLinkId(String pageLinkId) {
        this.pageLinkId = pageLinkId;
    }




}


