package com.mk.portal.framework.entity;
// Generated 2 Aug, 2015 6:35:28 AM by Hibernate Tools 3.2.2.GA



/**
 * PageFileMappingEntity generated by hbm2java
 */
public class PageFileMappingEntity  implements java.io.Serializable {


     private String id;
     private String siteId;
     private String pageId;
     private String fileId;

    public PageFileMappingEntity() {
    }

	
    public PageFileMappingEntity(String id, String siteId, String fileId) {
        this.id = id;
        this.siteId = siteId;
        this.fileId = fileId;
    }
    public PageFileMappingEntity(String id, String siteId, String pageId, String fileId) {
       this.id = id;
       this.siteId = siteId;
       this.pageId = pageId;
       this.fileId = fileId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
    public String getPageId() {
        return this.pageId;
    }
    
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }
    public String getFileId() {
        return this.fileId;
    }
    
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }




}


