package com.mk.portal.framework.entity;
// Generated 2 Aug, 2015 6:35:28 AM by Hibernate Tools 3.2.2.GA



/**
 * RolesEntity generated by hbm2java
 */
public class RolesEntity  implements java.io.Serializable {


     private int roleId;
     private String roleName;

    public RolesEntity() {
    }

    public RolesEntity(String roleName) {
       this.roleName = roleName;
    }
   
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }




}


