package com.mk.portal.framework.entity;
// Generated 11 Jul, 2015 10:57:56 PM by Hibernate Tools 3.2.2.GA



/**
 * SiteEntity generated by hbm2java
 */
public class SiteEntity  implements java.io.Serializable {


     private String siteId;
     private String siteName;
     private String siteTitle;
     private boolean enabled;
     private String siteTemplateId;
     private String siteUrl;
     private String HTMLVersion;
     private String charSet;

    public SiteEntity() {
    }

	
    public SiteEntity(String siteId, String siteName, boolean enabled, String siteTemplateId, String siteUrl, String HTMLVersion, String charSet) {
        this.siteId = siteId;
        this.siteName = siteName;
        this.enabled = enabled;
        this.siteTemplateId = siteTemplateId;
        this.siteUrl = siteUrl;
        this.HTMLVersion = HTMLVersion;
        this.charSet = charSet;
    }
    public SiteEntity(String siteId, String siteName, String siteTitle, boolean enabled, String siteTemplateId, String siteUrl, String HTMLVersion, String charSet) {
       this.siteId = siteId;
       this.siteName = siteName;
       this.siteTitle = siteTitle;
       this.enabled = enabled;
       this.siteTemplateId = siteTemplateId;
       this.siteUrl = siteUrl;
       this.HTMLVersion = HTMLVersion;
       this.charSet = charSet;
    }
   
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
    public String getSiteName() {
        return this.siteName;
    }
    
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
    public String getSiteTitle() {
        return this.siteTitle;
    }
    
    public void setSiteTitle(String siteTitle) {
        this.siteTitle = siteTitle;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public String getSiteTemplateId() {
        return this.siteTemplateId;
    }
    
    public void setSiteTemplateId(String siteTemplateId) {
        this.siteTemplateId = siteTemplateId;
    }
    public String getSiteUrl() {
        return this.siteUrl;
    }
    
    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl;
    }
    public String getHTMLVersion() {
        return this.HTMLVersion;
    }
    
    public void setHTMLVersion(String HTMLVersion) {
        this.HTMLVersion = HTMLVersion;
    }
    public String getCharSet() {
        return this.charSet;
    }
    
    public void setCharSet(String charSet) {
        this.charSet = charSet;
    }




}


