package com.mk.portal.framework.entity;
// Generated 16 Jul, 2015 3:51:50 PM by Hibernate Tools 3.2.2.GA



/**
 * WidgetEntity generated by hbm2java
 */
public class WidgetEntity  implements java.io.Serializable {


     private String id;
     private String name;
     private String uiPath;
     private String title;

    public WidgetEntity() {
    }

	
    public WidgetEntity(String id, String name, String title) {
        this.id = id;
        this.name = name;
        this.title = title;
    }
    public WidgetEntity(String id, String name, String uiPath, String title) {
       this.id = id;
       this.name = name;
       this.uiPath = uiPath;
       this.title = title;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUiPath() {
        return this.uiPath;
    }
    
    public void setUiPath(String uiPath) {
        this.uiPath = uiPath;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


