package com.mk.portal.framework.entity;
// Generated 6 Aug, 2015 5:39:58 PM by Hibernate Tools 3.2.2.GA



/**
 * WidgetInstancePropertyEntity generated by hbm2java
 */
public class WidgetInstancePropertyEntity  implements java.io.Serializable {


     private String id;
     private String widgetInstanceId;
     private String name;
     private String value;

    public WidgetInstancePropertyEntity() {
    }

    public WidgetInstancePropertyEntity(String id, String widgetInstanceId, String name, String value) {
       this.id = id;
       this.widgetInstanceId = widgetInstanceId;
       this.name = name;
       this.value = value;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getWidgetInstanceId() {
        return this.widgetInstanceId;
    }
    
    public void setWidgetInstanceId(String widgetInstanceId) {
        this.widgetInstanceId = widgetInstanceId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


