package com.mk.portal.framework.entity;
// Generated 16 Jul, 2015 3:51:50 PM by Hibernate Tools 3.2.2.GA



/**
 * WidgetPageMappingEntity generated by hbm2java
 */
public class WidgetPageMappingEntity  implements java.io.Serializable {


     private String widgetId;
     private String pageId;
     private String area;
     private int order;

    public WidgetPageMappingEntity() {
    }

	
    public WidgetPageMappingEntity(String widgetId, String pageId) {
        this.widgetId = widgetId;
        this.pageId = pageId;
    }
    public WidgetPageMappingEntity(String widgetId, String pageId, String area, int order) {
       this.widgetId = widgetId;
       this.pageId = pageId;
       this.area = area;
       this.order = order;
    }
   
    public String getWidgetId() {
        return this.widgetId;
    }
    
    public void setWidgetId(String widgetId) {
        this.widgetId = widgetId;
    }
    public String getPageId() {
        return this.pageId;
    }
    
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public int getOrder() {
        return this.order;
    }
    
    public void setOrder(int order) {
        this.order = order;
    }




}


