package com.mk.portal.framework.entity;
// Generated 6 Aug, 2015 5:39:58 PM by Hibernate Tools 3.2.2.GA



/**
 * WidgetEntity generated by hbm2java
 */
public class WidgetEntity  implements java.io.Serializable {


     private String id;
     private String name;
     private String title;

    public WidgetEntity() {
    }

    public WidgetEntity(String id, String name, String title) {
       this.id = id;
       this.name = name;
       this.title = title;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


