package com.mk.portal.framework.entity;
// Generated 6 Aug, 2015 5:39:58 PM by Hibernate Tools 3.2.2.GA



/**
 * WidgetPropertyEntity generated by hbm2java
 */
public class WidgetPropertyEntity  implements java.io.Serializable {


     private String id;
     private String widgetId;
     private String propertyName;
     private String requiredFlag;
     private String defaultValue;

    public WidgetPropertyEntity() {
    }

    public WidgetPropertyEntity(String id, String widgetId, String propertyName, String requiredFlag, String defaultValue) {
       this.id = id;
       this.widgetId = widgetId;
       this.propertyName = propertyName;
       this.requiredFlag = requiredFlag;
       this.defaultValue = defaultValue;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getWidgetId() {
        return this.widgetId;
    }
    
    public void setWidgetId(String widgetId) {
        this.widgetId = widgetId;
    }
    public String getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }
    public String getRequiredFlag() {
        return this.requiredFlag;
    }
    
    public void setRequiredFlag(String requiredFlag) {
        this.requiredFlag = requiredFlag;
    }
    public String getDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }




}


